import aiosqlite
import asyncpg
import logging
import time
import os
from datetime import datetime
from core.config import DATABASE_URL, VIP_GROUP_ID, DRIVER_GROUP_ID

logger = logging.getLogger(__name__)


class Database:
    def __init__(self):
        self.db_url = DATABASE_URL
        self.is_postgres = self.db_url.startswith("postgres")
        self._cache = {}
        self._last_cache_time = 0
        self.CACHE_TTL = 60  # 1 daqiqa
        self.pool = None
        self.conn = None

    async def connect(self):
        if self.is_postgres:
            try:
                self.pool = await asyncpg.create_pool(self.db_url)
                logger.info("Connected to PostgreSQL")
            except Exception as e:
                logger.critical(f"PostgreSQL Connection Failed: {e}")
                raise e
        else:
            # SQLite (Local Backup)
            logger.info(f"Using SQLite: {self.db_url}")
            path = self.db_url.replace("sqlite:///", "")
            self.conn = await aiosqlite.connect(path)
            self.conn.row_factory = aiosqlite.Row

    async def _execute(self, query, params=(), commit=False, fetch_one=False, fetch_all=False):
        # Parametrlar formatini o'zgartirish (SQLite '?' -> Postgres '$1', '$2')
        if self.is_postgres:
            # Oddiy replace qilsak xato bo'lishi mumkin, lekin hozircha oddiy yechim
            # Bizning querylarimizda ? belgisi faqat parametr uchun ishlatilgan
            idx = 1
            while '?' in query:
                query = query.replace('?', f'${idx}', 1)
                idx += 1
            
            try:
                async with self.pool.acquire() as conn:
                    if fetch_one:
                        row = await conn.fetchrow(query, *params)
                        return dict(row) if row else None
                    elif fetch_all:
                        rows = await conn.fetch(query, *params)
                        return [dict(r) for r in rows]
                    else:
                        # INSERT/UPDATE/DELETE
                        # Agar RETURNING id bo'lsa (oxirgi ID kerak bo'lsa)
                        if "INSERT" in query and "RETURNING" not in query and ("id" in query.lower() or "orders" in query.lower() or "payments" in query.lower()):
                            # Postgres da lastrowid yo'q, shuning uchun RETURNING id qo'shamiz
                            # Faqat specific tablelar uchun
                            if "orders" in query or "payments" in query:
                                query += " RETURNING id"
                                val = await conn.fetchval(query, *params)
                                return val
                            else:
                                await conn.execute(query, *params)
                                return True
                        
                        # Agar allaqachon returning bo'lsa
                        if "RETURNING" in query:
                             val = await conn.fetchval(query, *params)
                             return val

                        result = await conn.execute(query, *params)
                        return True
            except Exception as e:
                logger.error(f"PG Error: {query} | Params: {params} | {e}")
                return None
        else:
            # SQLite (Persistent connection)
            try:
                # To'g'ridan-to'g'ri bitta ulanishni ishlatsak tezlik juda oshadi
                async with self.conn.execute(query, params) as cursor:
                    result = None
                    if fetch_one:
                        row = await cursor.fetchone()
                        result = dict(row) if row else None
                    elif fetch_all:
                        rows = await cursor.fetchall()
                        result = [dict(r) for r in rows]
                    else:
                        result = cursor.lastrowid if cursor.lastrowid else True

                if commit:
                    await self.conn.commit()

                return result
            except Exception as e:
                logger.error(f"SQLite Error: {query} | Params: {params} | {e}")
                return None

    async def init(self):
        await self.connect()
        
        # Postgres da table yaratishda ozgina farq bor (BIGINT PRIMARY KEY AUTOINCREMENT -> SERIAL/BIGSERIAL)
        # Hozircha oddiyroq yondashamiz: IF NOT EXISTS bilan
        pk_type = "BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" if self.is_postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"
        bigint = "BIGINT" if self.is_postgres else "BIGINT"
        text = "TEXT"
        timestamp = "TIMESTAMP"
        
        # Drivers Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS drivers (
                telegram_id BIGINT PRIMARY KEY,
                full_name TEXT,
                phone TEXT,
                car_type TEXT,
                has_license TEXT,
                balance INTEGER DEFAULT 0,
                rating REAL DEFAULT 5.0,
                rating_count INTEGER DEFAULT 0,
                status TEXT DEFAULT 'pending',
                joined_at {timestamp},
                invite_count INTEGER DEFAULT 0,
                subscription_end {timestamp},
                referred_by BIGINT DEFAULT NULL
            )
        """, commit=True)

        # Passengers Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS passengers (
                telegram_id BIGINT PRIMARY KEY,
                full_name TEXT,
                phone TEXT,
                status TEXT DEFAULT 'active',
                is_vip INTEGER DEFAULT 0,
                joined_at {timestamp},
                referred_by BIGINT DEFAULT NULL
            )
        """, commit=True)

        # Orders Table
        # Postgresda 'user' keyword, shuning uchun user_id ishlatamiz (to'g'ri)
        # ID uchun SERIAL ishlatish yaxshiroq
        id_def = "SERIAL PRIMARY KEY" if self.is_postgres else "INTEGER PRIMARY KEY AUTOINCREMENT"
        
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS orders (
                id {id_def},
                user_id BIGINT,
                type TEXT,
                status TEXT DEFAULT 'pending',
                from_loc TEXT,
                to_loc TEXT,
                time_val TEXT,
                details TEXT,
                voice_file_id TEXT DEFAULT NULL,
                phone TEXT,
                price INTEGER DEFAULT 0,
                driver_id BIGINT DEFAULT NULL,
                lat REAL DEFAULT NULL,
                lon REAL DEFAULT NULL,
                created_at {timestamp}
            )
        """, commit=True)

        # Payments Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS payments (
                id {id_def},
                user_id BIGINT,
                amount INTEGER DEFAULT 0,
                photo_id TEXT,
                status TEXT DEFAULT 'pending',
                created_at {timestamp}
            )
        """, commit=True)

        # Settings Table
        await self._execute("""
            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT
            )
        """, commit=True)

        # Blacklist Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS blacklist (
                user_id BIGINT PRIMARY KEY,
                reason TEXT,
                created_at {timestamp}
            )
        """, commit=True)

        # === AVTO XABAR TABLES ===
        # Accounts Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS accounts (
                id {id_def},
                user_id BIGINT,
                phone TEXT,
                name TEXT DEFAULT 'Bosh profil',
                session_string TEXT,
                status TEXT DEFAULT 'active'
            )
        """, commit=True)

        # Ad Messages Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS ad_messages (
                id {id_def},
                user_id BIGINT,
                account_id INTEGER,
                text TEXT,
                groups TEXT,
                photo_id TEXT DEFAULT NULL,
                interval_min INTEGER DEFAULT 5,
                last_sent {timestamp} DEFAULT NULL,
                is_active INTEGER DEFAULT 0,
                expires_at {timestamp} DEFAULT NULL
            )
        """, commit=True)

        # Bot Groups Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS bot_groups (
                chat_id BIGINT PRIMARY KEY,
                title TEXT,
                added_at {timestamp} DEFAULT CURRENT_TIMESTAMP
            )
        """, commit=True)

        # Promocodes Table
        await self._execute(f"""
            CREATE TABLE IF NOT EXISTS promocodes (
                code TEXT PRIMARY KEY,
                amount INTEGER,
                max_uses INTEGER DEFAULT 1,
                used_count INTEGER DEFAULT 0,
                expires_at {timestamp}
            )
        """, commit=True)
        
        # --- AUTO MIGRATION (SQLite Only) ---
        if not self.is_postgres:
            expected_tables = {
                "drivers": {
                    "telegram_id": "BIGINT", "full_name": "TEXT", "phone": "TEXT", "car_type": "TEXT",
                    "has_license": "TEXT", "balance": "INTEGER", "rating": "REAL", "rating_count": "INTEGER",
                    "status": "TEXT", "joined_at": "TIMESTAMP", "invite_count": "INTEGER", 
                    "subscription_end": "TIMESTAMP", "referred_by": "BIGINT"
                },
                "passengers": {
                    "telegram_id": "BIGINT", "full_name": "TEXT", "phone": "TEXT", "status": "TEXT",
                    "is_vip": "INTEGER", "joined_at": "TIMESTAMP", "referred_by": "BIGINT"
                },
                "orders": {
                    "id": "INTEGER", "user_id": "BIGINT", "type": "TEXT", "status": "TEXT",
                    "from_loc": "TEXT", "to_loc": "TEXT", "time_val": "TEXT", "details": "TEXT",
                    "voice_file_id": "TEXT", "phone": "TEXT", "price": "INTEGER", "driver_id": "BIGINT",
                    "lat": "REAL", "lon": "REAL", "created_at": "TIMESTAMP"
                },
                "payments": {
                    "id": "INTEGER", "user_id": "BIGINT", "amount": "INTEGER", "photo_id": "TEXT",
                    "status": "TEXT", "created_at": "TIMESTAMP"
                },
                "blacklist": {
                    "user_id": "BIGINT", "reason": "TEXT", "created_at": "TIMESTAMP"
                },
                "ad_messages": {
                    "expires_at": "TIMESTAMP"
                },
                "bot_groups": {
                    "chat_id": "BIGINT", "title": "TEXT", "added_at": "TIMESTAMP"
                }
            }
            
            for table_name, columns in expected_tables.items():
                try:
                    # Get existing columns
                    existing_columns_info = await self._execute(f"PRAGMA table_info({table_name})", fetch_all=True)
                    if existing_columns_info:
                        existing_cols = {col['name'] for col in existing_columns_info}
                        
                        # Find missing columns
                        for col_name, col_type in columns.items():
                            if col_name not in existing_cols:
                                logger.info(f"Adding missing column {col_name} to {table_name}")
                                await self._execute(f"ALTER TABLE {table_name} ADD COLUMN {col_name} {col_type}", commit=True)
                except Exception as e:
                    logger.error(f"Migration error on table {table_name}: {e}")
        # --- END AUTO MIGRATION ---
        
        # Defaults initialization
        defaults = [
            ('min_price_taxi', '20000'),
            ('min_price_delivery', '15000'),
            ('driver_subscription_fee', '20000'),
            ('mandatory_sub', 'off'),
            ('btn_taxi', '🚖 Taxi chaqirish'),
            ('btn_delivery', '📦 Yetkazib berish'),
            ('btn_group', '🌟 VIP Buyurtma'),
            ('btn_profile', '👤 Profilim'),
            ('btn_back', '⬅️ Ortga'),
            ('payment_card', '9860 3501 4062 9212'),
            ('payment_card_owner', 'Usmonov Samandar'),
            ('vip_group_ids', str(VIP_GROUP_ID)),
            ('free_group_ids', str(DRIVER_GROUP_ID)),
            ('avto_xabar_fee', '25000') # 30 kunlik narxi
        ]

        for key, val in defaults:
            # Postgresda INSERT OR IGNORE sintaksisi yo'q -> ON CONFLICT DO NOTHING
            if self.is_postgres:
                await self._execute(
                    "INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT (key) DO NOTHING",
                    (key, val),
                    commit=True
                )
            else:
                 await self._execute(
                    "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)",
                    (key, val),
                    commit=True
                )

        await self.refresh_cache()

    # --- SETTINGS & CACHE ---
    async def refresh_cache(self):
        rows = await self._execute("SELECT * FROM settings", fetch_all=True)
        if rows:
            self._cache = {row['key']: row['value'] for row in rows}
            self._last_cache_time = time.time()
            logger.debug("Settings cache refreshed")

    async def get_setting(self, key, default=None):
        if time.time() - self._last_cache_time > self.CACHE_TTL:
            await self.refresh_cache()
        return self._cache.get(key, default)

    async def set_setting(self, key, value):
        if self.is_postgres:
            await self._execute(
                 "INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
                 (key, str(value)),
                 commit=True
            )
        else:
            await self._execute(
                "INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)",
                (key, str(value)),
                commit=True
            )
        await self.refresh_cache()
        return True

    # --- PASSENGERS ---
    async def get_passenger(self, telegram_id):
        return await self._execute(
            "SELECT * FROM passengers WHERE telegram_id = ?",
            (telegram_id,),
            fetch_one=True
        )

    async def register_passenger(self, telegram_id, name, phone, ref_by=None):
        if self.is_postgres:
             return await self._execute(
                """
                INSERT INTO passengers 
                (telegram_id, full_name, phone, joined_at, referred_by) 
                VALUES (?, ?, ?, ?, ?)
                ON CONFLICT (telegram_id) DO UPDATE 
                SET full_name = EXCLUDED.full_name, phone = EXCLUDED.phone
                """,
                (telegram_id, name, phone, datetime.now(), ref_by),
                commit=True
            )
        else:
            return await self._execute(
                """
                INSERT OR REPLACE INTO passengers 
                (telegram_id, full_name, phone, joined_at, referred_by) 
                VALUES (?, ?, ?, ?, ?)
                """,
                (telegram_id, name, phone, datetime.now(), ref_by),
                commit=True
            )

    async def update_passenger_name(self, tid, name):
        return await self._execute(
            "UPDATE passengers SET full_name = ? WHERE telegram_id = ?",
            (name, tid),
            commit=True
        )

    # --- DRIVERS ---
    async def get_driver(self, telegram_id):
        return await self._execute(
            "SELECT * FROM drivers WHERE telegram_id = ?",
            (telegram_id,),
            fetch_one=True
        )

    async def register_driver(self, tid, name, phone, car, license, ref_by=None):
        if self.is_postgres:
            return await self._execute(
                """
                INSERT INTO drivers 
                (telegram_id, full_name, phone, car_type, has_license, status, joined_at, referred_by) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT (telegram_id) DO UPDATE 
                SET full_name = EXCLUDED.full_name, phone = EXCLUDED.phone, 
                    car_type = EXCLUDED.car_type, has_license = EXCLUDED.has_license
                """,
                (tid, name, phone, car, license, 'pending', datetime.now(), ref_by),
                commit=True
            )
        else:
            return await self._execute(
                """
                INSERT OR REPLACE INTO drivers 
                (telegram_id, full_name, phone, car_type, has_license, status, joined_at, referred_by) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (tid, name, phone, car, license, 'pending', datetime.now(), ref_by),
                commit=True
            )

    async def add_driver_invite(self, driver_id):
        return await self._execute(
            "UPDATE drivers SET invite_count = invite_count + 1 WHERE telegram_id = ?",
            (driver_id,),
            commit=True
        )

    async def update_driver_subscription(self, driver_id, end_date):
        return await self._execute(
            "UPDATE drivers SET status = 'active', subscription_end = ? WHERE telegram_id = ?",
            (end_date, driver_id),
            commit=True
        )

    async def update_driver_status(self, tid, status):
        return await self._execute(
            "UPDATE drivers SET status = ? WHERE telegram_id = ?",
            (status, tid),
            commit=True
        )

    async def update_driver_balance(self, tid, amount, mode='add'):
        if mode == 'add':
            return await self._execute(
                "UPDATE drivers SET balance = balance + ? WHERE telegram_id = ?",
                (amount, tid),
                commit=True
            )
        return await self._execute(
            "UPDATE drivers SET balance = ? WHERE telegram_id = ?",
            (amount, tid),
            commit=True
        )

    async def update_driver_name(self, tid, name):
        return await self._execute(
            "UPDATE drivers SET full_name = ? WHERE telegram_id = ?",
            (name, tid),
            commit=True
        )

    # --- ORDERS ---
    async def create_order(self, uid, otype, floc, tloc, price, tval, details, phone, lat=None, lon=None, voice_id=None):
        # Postgres orders table has SERIAL ID, so we pass query implicitly
        # Note: In Postgres insert we might returning id inside _execute
        return await self._execute(
            """
            INSERT INTO orders 
            (user_id, type, status, from_loc, to_loc, time_val, details, phone, price, lat, lon, voice_file_id, created_at) 
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (uid, otype, 'pending', floc, tloc, tval, details, phone, price, lat, lon, voice_id, datetime.now()),
            commit=True
        )

    async def get_order(self, oid):
        return await self._execute(
            "SELECT * FROM orders WHERE id = ?",
            (oid,),
            fetch_one=True
        )

    async def update_order_driver(self, oid, did):
        return await self._execute(
            "UPDATE orders SET driver_id = ?, status = 'accepted' WHERE id = ?",
            (did, oid),
            commit=True
        )

    async def update_order_status(self, oid, status):
        return await self._execute(
            "UPDATE orders SET status = ? WHERE id = ?",
            (status, oid),
            commit=True
        )

    # --- STATS & LISTS ---
    async def get_stats(self):
        stats = {}
        today = datetime.now().strftime('%Y-%m-%d')
        month = datetime.now().strftime('%Y-%m')

        # User counts
        d_count = await self._execute("SELECT COUNT(*) as c FROM drivers", fetch_one=True)
        stats['total_drivers'] = d_count['c'] if d_count else 0

        p_count = await self._execute("SELECT COUNT(*) as c FROM passengers", fetch_one=True)
        stats['total_passengers'] = p_count['c'] if p_count else 0

        o_count = await self._execute("SELECT COUNT(*) as c FROM orders", fetch_one=True)
        stats['total_orders'] = o_count['c'] if o_count else 0

        # Daily growth
        if self.is_postgres:
            d_today = await self._execute("SELECT COUNT(*) as c FROM drivers WHERE joined_at::text LIKE ?", (f"{today}%",), fetch_one=True)
            p_today = await self._execute("SELECT COUNT(*) as c FROM passengers WHERE joined_at::text LIKE ?", (f"{today}%",), fetch_one=True)
            o_today = await self._execute("SELECT COUNT(*) as c FROM orders WHERE created_at::text LIKE ?", (f"{today}%",), fetch_one=True)
        else:
            d_today = await self._execute("SELECT COUNT(*) as c FROM drivers WHERE joined_at LIKE ?", (f"{today}%",), fetch_one=True)
            p_today = await self._execute("SELECT COUNT(*) as c FROM passengers WHERE joined_at LIKE ?", (f"{today}%",), fetch_one=True)
            o_today = await self._execute("SELECT COUNT(*) as c FROM orders WHERE created_at LIKE ?", (f"{today}%",), fetch_one=True)
        
        stats['new_drivers_today'] = d_today['c'] if d_today else 0
        stats['new_passengers_today'] = p_today['c'] if p_today else 0
        stats['today_orders'] = o_today['c'] if o_today else 0

        # Revenue
        rev_total = await self._execute("SELECT SUM(amount) as s FROM payments WHERE status = 'approved'", fetch_one=True)
        stats['total_revenue'] = rev_total['s'] if rev_total and rev_total['s'] else 0

        if self.is_postgres:
            rev_today = await self._execute("SELECT SUM(amount) as s FROM payments WHERE status = 'approved' AND created_at::text LIKE ?", (f"{today}%",), fetch_one=True)
            rev_month = await self._execute("SELECT SUM(amount) as s FROM payments WHERE status = 'approved' AND created_at::text LIKE ?", (f"{month}%",), fetch_one=True)
        else:
            rev_today = await self._execute("SELECT SUM(amount) as s FROM payments WHERE status = 'approved' AND created_at LIKE ?", (f"{today}%",), fetch_one=True)
            rev_month = await self._execute("SELECT SUM(amount) as s FROM payments WHERE status = 'approved' AND created_at LIKE ?", (f"{month}%",), fetch_one=True)
            
        stats['today_revenue'] = rev_today['s'] if rev_today and rev_today['s'] else 0
        stats['month_revenue'] = rev_month['s'] if rev_month and rev_month['s'] else 0

        faol = await self._execute("SELECT COUNT(*) as c FROM drivers WHERE status = 'active'", fetch_one=True)
        stats['active_drivers'] = faol['c'] if faol else 0

        return stats

    async def get_all_users_for_broadcast(self):
        dids = await self._execute("SELECT telegram_id FROM drivers", fetch_all=True)
        pids = await self._execute("SELECT telegram_id FROM passengers", fetch_all=True)
        ids = [d['telegram_id'] for d in dids or []] + [p['telegram_id'] for p in pids or []]
        return list(set(ids))

    async def get_all_drivers(self, limit=10):
        return await self._execute(
            "SELECT * FROM drivers ORDER BY joined_at DESC LIMIT ?",
            (limit,),
            fetch_all=True
        )

    async def get_driver_orders(self, did, limit=10):
        return await self._execute(
            "SELECT * FROM orders WHERE driver_id = ? ORDER BY created_at DESC LIMIT ?",
            (did, limit),
            fetch_all=True
        )

    async def get_expired_drivers(self):
        now = datetime.now()
        return await self._execute(
            """
            SELECT * FROM drivers 
            WHERE status = 'active' 
            AND subscription_end IS NOT NULL 
            AND subscription_end < ?
            """,
            (now,),
            fetch_all=True
        )

    async def get_recent_orders(self, limit=10):
        return await self._execute("""
            SELECT o.*, p.full_name as passenger_name, d.full_name as driver_name
            FROM orders o
            LEFT JOIN passengers p ON o.user_id = p.telegram_id
            LEFT JOIN drivers d ON o.driver_id = d.telegram_id
            ORDER BY o.created_at DESC LIMIT ?
        """, (limit,), fetch_all=True)

    async def delete_order(self, oid):
        return await self._execute("DELETE FROM orders WHERE id = ?", (oid,), commit=True)

    # --- PAYMENTS ---
    async def add_payment(self, user_id, amount, photo_id):
        # Postgres insert to return ID handled in _execute
        return await self._execute(
            "INSERT INTO payments (user_id, amount, photo_id, created_at) VALUES (?, ?, ?, ?)",
            (user_id, amount, photo_id, datetime.now()),
            commit=True
        )

    async def get_pending_payments(self):
        return await self._execute(
            """
            SELECT p.*, d.full_name 
            FROM payments p 
            JOIN drivers d ON p.user_id = d.telegram_id 
            WHERE p.status = 'pending'
            """,
            fetch_all=True
        )

    async def get_pending_orders(self, limit=20):
        return await self._execute(
            """
            SELECT o.*, p.full_name as passenger_name 
            FROM orders o 
            LEFT JOIN passengers p ON o.user_id = p.telegram_id 
            WHERE o.status = 'pending' 
            ORDER BY o.created_at DESC LIMIT ?
            """,
            (limit,),
            fetch_all=True
        )

    # --- PROMOCODES ---
    async def create_promocode(self, code, amount, max_uses=1, expires_at=None):
        return await self._execute(
            "INSERT INTO promocodes (code, amount, max_uses, expires_at) VALUES (?, ?, ?, ?)",
            (code.upper(), amount, max_uses, expires_at),
            commit=True
        )

    async def get_promocode(self, code):
        return await self._execute("SELECT * FROM promocodes WHERE code = ?", (code.upper(),), fetch_one=True)

    async def use_promocode(self, code):
        return await self._execute(
            "UPDATE promocodes SET used_count = used_count + 1 WHERE code = ?",
            (code.upper(),),
            commit=True
        )

    async def get_all_promocodes(self):
        return await self._execute("SELECT * FROM promocodes ORDER BY expires_at DESC", fetch_all=True)

    async def delete_promocode(self, code):
        return await self._execute("DELETE FROM promocodes WHERE code = ?", (code.upper(),), commit=True)

    async def update_payment_status(self, pid, status):
        return await self._execute(
            "UPDATE payments SET status = ? WHERE id = ?",
            (status, pid),
            commit=True
        )

    async def get_payments_history(self, limit=50):
        return await self._execute(
            """
            SELECT p.*, d.full_name 
            FROM payments p 
            LEFT JOIN drivers d ON p.user_id = d.telegram_id 
            ORDER BY p.created_at DESC LIMIT ?
            """,
            (limit,),
            fetch_all=True
        )

    async def get_drivers_by_status(self, status, limit=50):
        return await self._execute(
            "SELECT * FROM drivers WHERE status = ? ORDER BY joined_at DESC LIMIT ?",
            (status, limit),
            fetch_all=True
        )

    # --- BLACKLIST ---
    async def add_to_blacklist(self, uid, reason="Admin block"):
        if self.is_postgres:
            return await self._execute(
                "INSERT INTO blacklist (user_id, reason, created_at) VALUES (?, ?, ?) ON CONFLICT (user_id) DO UPDATE SET reason = EXCLUDED.reason",
                (uid, reason, datetime.now()),
                commit=True
            )
        else:
            return await self._execute(
                "INSERT OR REPLACE INTO blacklist (user_id, reason, created_at) VALUES (?, ?, ?)",
                (uid, reason, datetime.now()),
                commit=True
            )

    async def remove_from_blacklist(self, uid):
        return await self._execute(
            "DELETE FROM blacklist WHERE user_id = ?",
            (uid,),
            commit=True
        )

    async def is_blacklisted(self, uid):
        res = await self._execute(
            "SELECT user_id FROM blacklist WHERE user_id = ?",
            (uid,),
            fetch_one=True
        )
        return res is not None

    async def get_blacklist(self):
        return await self._execute("SELECT * FROM blacklist", fetch_all=True)

    # --- FOYDALANUVCHILARNI ROL BO'YICHA OLISH ---
    async def get_users_by_role(self, role, is_vip=False):
        if role == 'driver':
            if is_vip:
                return await self._execute(
                    "SELECT * FROM drivers WHERE status = 'active' ORDER BY joined_at DESC",
                    fetch_all=True
                )
            else:
                return await self._execute("SELECT * FROM drivers ORDER BY joined_at DESC", fetch_all=True)
        elif role == 'passenger':
            return await self._execute("SELECT * FROM passengers ORDER BY joined_at DESC", fetch_all=True)
        elif role == 'all':
            drivers = await self._execute(
                "SELECT *, 'driver' as role FROM drivers ORDER BY joined_at DESC",
                fetch_all=True
            ) or []
            passengers = await self._execute(
                "SELECT *, 'passenger' as role FROM passengers ORDER BY joined_at DESC",
                fetch_all=True
            ) or []
            return drivers + passengers
        else:
            return []

    async def get_all_passengers(self, limit=50):
        return await self._execute(
            "SELECT * FROM passengers ORDER BY joined_at DESC LIMIT ?",
            (limit,),
            fetch_all=True
        )

    async def get_driver_by_query(self, q):
        # CAST/conversion for LIKE
        if self.is_postgres:
             return await self._execute(
                "SELECT * FROM drivers WHERE telegram_id::text = ? OR phone LIKE ?",
                (str(q), f"%{q}%"),
                fetch_one=True
            )
        else:
             return await self._execute(
                "SELECT * FROM drivers WHERE telegram_id = ? OR phone LIKE ?",
                (q, f"%{q}%"),
                fetch_one=True
            )

    async def get_user_by_query(self, q):
        # We can implement simpler query here for unified search if needed, 
        # but reusing above is safer for logic
        d = await self.get_driver_by_query(q)
        if d:
            d = dict(d)
            d['role'] = 'driver'
            return d
        
        # Passenger search
        if self.is_postgres:
            p = await self._execute(
                "SELECT *, 'passenger' as role FROM passengers WHERE telegram_id::text = ? OR phone LIKE ?",
                (str(q), f"%{q}%"),
                fetch_one=True
            )
        else:
            p = await self._execute(
                "SELECT *, 'passenger' as role FROM passengers WHERE telegram_id = ? OR phone LIKE ?",
                (q, f"%{q}%"),
                fetch_one=True
            )
        return dict(p) if p else None


    # --- AVTO XABAR METHODS ---
    async def get_accounts(self, user_id):
        return await self._execute("SELECT * FROM accounts WHERE user_id = ?", (user_id,), fetch_all=True)

    async def save_account(self, user_id, phone, session_string, name="Bosh profil"):
        if self.is_postgres:
            return await self._execute(
                "INSERT INTO accounts (user_id, phone, session_string, name) VALUES (?, ?, ?, ?) RETURNING id",
                (user_id, phone, session_string, name),
                commit=True
            )
        else:
            return await self._execute(
                "INSERT INTO accounts (user_id, phone, session_string, name) VALUES (?, ?, ?, ?)",
                (user_id, phone, session_string, name),
                commit=True
            )

    async def delete_account(self, acc_id):
        return await self._execute("DELETE FROM accounts WHERE id = ?", (acc_id,), commit=True)

    async def get_ad_message(self, user_id):
        return await self._execute("SELECT * FROM ad_messages WHERE user_id = ?", (user_id,), fetch_one=True)

    async def update_ad_message(self, user_id, text=None, photo_id=None, interval=None, is_active=None, **kwargs):
        ad = await self.get_ad_message(user_id)
        
        updates = []
        params = []
        
        if text is not None:
            updates.append("text = ?")
            params.append(text)
        if photo_id is not None:
            updates.append("photo_id = ?")
            params.append(photo_id)
        if interval is not None:
            updates.append("interval_min = ?")
            params.append(interval)
        if is_active is not None:
            updates.append("is_active = ?")
            params.append(is_active)
        if 'expires_at' in kwargs:
            updates.append("expires_at = ?")
            params.append(kwargs['expires_at'])
            
        if not ad:
            # Create new
            initial_text = text or ""
            initial_photo = photo_id
            initial_int = interval or 5
            initial_active = is_active if is_active is not None else 1
            initial_exp = kwargs.get('expires_at')
            
            return await self._execute(
                "INSERT INTO ad_messages (user_id, text, photo_id, interval_min, is_active, expires_at) VALUES (?, ?, ?, ?, ?, ?)",
                (user_id, initial_text, initial_photo, initial_int, initial_active, initial_exp),
                commit=True
            )
        else:
            # Update existing
            if not updates: return True
            
            query = f"UPDATE ad_messages SET {', '.join(updates)} WHERE user_id = ?"
            params.append(user_id)
            return await self._execute(query, tuple(params), commit=True)

    async def get_all_active_ads(self):
        return await self._execute("SELECT * FROM ad_messages WHERE is_active = 1", fetch_all=True)

    async def is_ad_sub_active(self, user_id):
        ad = await self.get_ad_message(user_id)
        if not ad:
            return False
            
        if 'expires_at' not in ad or not ad['expires_at']:
            return False
            
        exp = ad['expires_at']
        if isinstance(exp, str):
            try:
                exp = datetime.strptime(exp, '%Y-%m-%d %H:%M:%S.%f')
            except:
                try:
                    exp = datetime.strptime(exp, '%Y-%m-%d %H:%M:%S')
                except:
                    return False
        
        if isinstance(exp, datetime) and exp > datetime.now():
            return True
            
        return False

    async def save_bot_group(self, chat_id: int, title: str):
        logger.info(f"Database: Saving bot group {chat_id} - {title}")
        return await self._execute(
            "INSERT OR REPLACE INTO bot_groups (chat_id, title) VALUES (?, ?)",
            (chat_id, title),
            commit=True
        )

    async def get_bot_groups(self):
        rows = await self._execute("SELECT chat_id FROM bot_groups", fetch_all=True)
        if not rows: return []
        return [r['chat_id'] for r in rows if r and 'chat_id' in r]
        
    async def remove_bot_group(self, chat_id: int):
        logger.info(f"Database: Removing bot group {chat_id}")
        return await self._execute("DELETE FROM bot_groups WHERE chat_id = ?", (chat_id,), commit=True)

# Global instance
db = Database()


# Global wrapper functions (qulaylik uchun)
async def _execute(*args, **kwargs): return await db._execute(*args, **kwargs)
async def init_db(): await db.init()
async def get_setting(k, d=None): return await db.get_setting(k, d)
async def set_setting(k, v): return await db.set_setting(k, v)
async def get_all_settings(): return db._cache
async def get_passenger(tid): return await db.get_passenger(tid)
async def register_passenger(tid, n, p, rb=None): return await db.register_passenger(tid, n, p, rb)
async def get_driver(tid): return await db.get_driver(tid)
async def register_driver(tid, n, p, c, l, rb=None): return await db.register_driver(tid, n, p, c, l, rb)
async def update_driver_status(tid, s): return await db.update_driver_status(tid, s)
async def update_driver_name(tid, n): return await db.update_driver_name(tid, n)
async def update_passenger_name(tid, n): return await db.update_passenger_name(tid, n)
async def create_order(uid, ot, fl, tl, pr, tv, det, ph, lat=None, lon=None, vi=None):
    return await db.create_order(uid, ot, fl, tl, pr, tv, det, ph, lat, lon, vi)
async def get_order(oid): return await db.get_order(oid)
async def update_order_driver(oid, did): return await db.update_order_driver(oid, did)
async def update_order_status(oid, s): return await db.update_order_status(oid, s)
async def get_stats(): return await db.get_stats()
async def get_all_users_for_broadcast(): return await db.get_all_users_for_broadcast()
async def get_all_drivers(limit=10): return await db.get_all_drivers(limit)
async def get_recent_orders(limit=10): return await db.get_recent_orders(limit)
async def update_driver_balance(tid, a, mode='add'): return await db.update_driver_balance(tid, a, mode)
async def update_driver_subscription(tid, ed): return await db.update_driver_subscription(tid, ed)
async def add_driver_invite(did): return await db.add_driver_invite(did)
async def get_driver_by_query(q): return await db.get_driver_by_query(q)
async def delete_order(oid): return await db.delete_order(oid)
async def get_user_by_query(q): return await db.get_user_by_query(q)
async def add_payment(uid, a, ph): return await db.add_payment(uid, a, ph)
async def get_pending_payments(): return await db.get_pending_payments()
async def update_payment_status(pid, s): return await db.update_payment_status(pid, s)
async def get_expired_drivers(): return await db.get_expired_drivers()
async def get_driver_orders(did, limit=10): return await db.get_driver_orders(did, limit)
async def get_users_by_role(role, is_vip=False): return await db.get_users_by_role(role, is_vip)
async def add_to_blacklist(uid, reason="Admin block"): return await db.add_to_blacklist(uid, reason)
async def remove_from_blacklist(uid): return await db.remove_from_blacklist(uid)
async def is_blacklisted(uid): return await db.is_blacklisted(uid)
async def get_blacklist(): return await db.get_blacklist()
async def get_drivers_by_status(status, limit=50): return await db.get_drivers_by_status(status, limit)
async def get_all_passengers(limit=50): return await db.get_all_passengers(limit)

# Avto Xabar wrappers
async def get_accounts(uid): return await db.get_accounts(uid)
async def save_account(uid, p, s, n): return await db.save_account(uid, p, s, n)
async def delete_account(aid): return await db.delete_account(aid)
async def get_ad_message(uid): return await db.get_ad_message(uid)
async def update_ad_message(uid, **kwargs): return await db.update_ad_message(uid, **kwargs)
async def get_all_active_ads(): return await db.get_all_active_ads()
async def is_ad_sub_active(uid): return await db.is_ad_sub_active(uid)

async def save_bot_group(chat_id, title): return await db.save_bot_group(chat_id, title)
async def get_bot_groups(): return await db.get_bot_groups()
async def remove_bot_group(chat_id): return await db.remove_bot_group(chat_id)

async def get_pending_orders(l=20): return await db.get_pending_orders(l)
async def create_promocode(c, a, m=1, e=None): return await db.create_promocode(c, a, m, e)
async def get_promocode(c): return await db.get_promocode(c)
async def use_promocode(c): return await db.use_promocode(c)
async def get_all_promocodes(): return await db.get_all_promocodes()
async def delete_promocode(c): return await db.delete_promocode(c)
